package com.douglas.APIHosital.enums;

public enum StatusAtendimento {
    AGUARDANDO_ATENDIMENTO,
    AGUARDANDO_MEDICO,
    EM_ANDAMENTO_MEDICO,
    AGUARDANDO_MEDICACAO,
    EM_MEDICACAO,
    AGUARDANDO_ALTA_MEDICA,
    CONCLUIDO
}
